nombre1 = input("Ingrese su nombre completo:")
print(nombre1)
edad1 = int(input("Ingrese su edad:"))
print(edad1)
sueldo = float(input("Ingrese su sueldo:"))
numero1 = float(100)
numero2 = float(25)
aumento = ((sueldo) * (numero2) / (numero1)) 
print(("se le va a aumentar"),(aumento),("a su sueldo"))
print(("El total seria de"),(sueldo) + (aumento))
